name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Generate ZIP
        run: |
          zip deployment.zip *.mjs
      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: primeiraFunCall
          zip_file: deployment.zip
          memory_size: 128
          timeout: 10
          handler: foobar
          role: arn:aws:iam::844686317146:role/service-role/primeiraFunCall-role-np4s0dnw
          runtime: nodejs20.x
